INSERT INTO `countries` (`id`, `name`) VALUES (1, 'Andorra');
INSERT INTO `countries` (`id`, `name`) VALUES (2, 'United Arab Emirates');
INSERT INTO `countries` (`id`, `name`) VALUES (3, 'Afghanistan');
INSERT INTO `countries` (`id`, `name`) VALUES (4, 'Antigua and Barbuda');
INSERT INTO `countries` (`id`, `name`) VALUES (6, 'Albania');
INSERT INTO `countries` (`id`, `name`) VALUES (7, 'Armenia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (9, 'Angola\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (11, 'Argentina\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (13, 'Austria\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (14, 'Australia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (17, 'Azerbaijan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (18, 'Bosnia and Herzegovina\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (19, 'Barbados\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (20, 'Bangladesh\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (21, 'Belgium\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (22, 'Burkina Faso\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (23, 'Bulgaria\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (24, 'Bahrain\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (26, 'Benin\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (29, 'Brunei Darussalam\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (30, 'Bolivia\r\nBolivia, Plurinational state of');
INSERT INTO `countries` (`id`, `name`) VALUES (31, 'Brazil\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (32, 'Bahamas\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (35, 'Botswana\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (36, 'Belarus\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (37, 'Belize\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (42, 'Congo\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (43, 'Switzerland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (44, 'Cote d\'Ivoire');
INSERT INTO `countries` (`id`, `name`) VALUES (46, 'Chile');
INSERT INTO `countries` (`id`, `name`) VALUES (47, 'Cameroon\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (48, 'China\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (49, 'Colombia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (50, 'Costa Rica\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (51, 'Cuba\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (52, 'Cape Verde\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (54, 'Cyprus\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (55, 'Czech Republic\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (56, 'Germany\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (57, 'Djibouti\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (58, 'Denmark\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (59, 'Dominica\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (60, 'Dominican Republic\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (61, 'Algeria\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (62, 'Ecuador\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (63, 'Estonia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (64, 'Egypt\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (67, 'Spain\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (68, 'Ethiopia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (69, 'Finland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (70, 'Fiji\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (72, 'Micronesia, Federated States of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (74, 'France\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (75, 'Gabon');
INSERT INTO `countries` (`id`, `name`) VALUES (76, 'United Kingdom');
INSERT INTO `countries` (`id`, `name`) VALUES (77, 'Grenada');
INSERT INTO `countries` (`id`, `name`) VALUES (78, 'Georgia');
INSERT INTO `countries` (`id`, `name`) VALUES (81, 'Ghana\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (83, 'Greenland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (84, 'Gambia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (85, 'Guinea\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (87, 'Equatorial Guinea\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (88, 'Greece\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (90, 'Guatemala\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (93, 'Guyana\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (96, 'Honduras\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (97, 'Croatia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (98, 'Haiti\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (99, 'Hungary\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (100, 'Indonesia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (101, 'Ireland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (102, 'Israel\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (104, 'India\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (106, 'Iraq\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (107, 'Iran, Islamic Republic of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (108, 'Iceland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (109, 'Italy');
INSERT INTO `countries` (`id`, `name`) VALUES (111, 'Jamaica\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (112, 'Jordan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (113, 'Japan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (114, 'Kenya\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (115, 'Kyrgyzstan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (116, 'Cambodia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (117, 'Kiribati\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (119, 'Saint Kitts and Nevis\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (120, 'Korea, Democratic People&#39;s Republic of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (121, 'Korea, Republic of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (122, 'Kuwait\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (123, 'Cayman Islands\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (124, 'Kazakhstan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (125, 'Lao People&#39;s Democratic Republic\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (126, 'Lebanon\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (128, 'Liechtenstein\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (131, 'Lesotho\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (132, 'Lithuania\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (133, 'Luxembourg\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (134, 'Latvia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (135, 'Libyan Arab Jamahiriya\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (136, 'Morocco\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (138, 'Moldova, Republic of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (141, 'Madagascar\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (143, 'Macedonia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (144, 'Mali\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (145, 'Myanmar\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (146, 'Mongolia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (147, 'Macao\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (150, 'Mauritania\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (153, 'Mauritius\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (154, 'Maldives\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (155, 'Malawi\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (156, 'Mexico\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (157, 'Malaysia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (158, 'Mozambique\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (159, 'Namibia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (163, 'Nigeria\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (164, 'Nicaragua\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (165, 'Netherlands\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (166, 'Norway');
INSERT INTO `countries` (`id`, `name`) VALUES (171, 'Oman\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (172, 'Panama\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (173, 'Peru\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (175, 'Papua New Guinea\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (176, 'Philippines\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (177, 'Pakistan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (178, 'Poland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (183, 'Portugal\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (185, 'Paraguay\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (186, 'Qatar\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (188, 'Romania\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (190, 'Russian Federation\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (192, 'Saudi Arabia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (193, 'Solomon Islands\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (195, 'Sudan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (196, 'Sweden\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (199, 'Slovenia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (201, 'Slovakia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (202, 'Sierra Leone\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (203, 'San Marino\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (204, 'Senegal\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (205, 'Somalia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (206, 'Suriname\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (208, 'El Salvador\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (209, 'Syrian Arab Republic\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (210, 'Swaziland\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (212, 'Chad');
INSERT INTO `countries` (`id`, `name`) VALUES (214, 'Togo');
INSERT INTO `countries` (`id`, `name`) VALUES (215, 'Thailand');
INSERT INTO `countries` (`id`, `name`) VALUES (216, 'Tajikistan');
INSERT INTO `countries` (`id`, `name`) VALUES (219, 'Turkmenistan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (220, 'Tunisia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (222, 'Turkey');
INSERT INTO `countries` (`id`, `name`) VALUES (223, 'Trinidad and Tobago\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (225, 'Taiwan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (226, 'Tanzania, United Republic of\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (227, 'Ukraine\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (228, 'Uganda\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (230, 'United States\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (231, 'Uruguay\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (232, 'Uzbekistan\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (235, 'Venezuela, Bolivarian Republic of');
INSERT INTO `countries` (`id`, `name`) VALUES (238, 'Viet Nam');
INSERT INTO `countries` (`id`, `name`) VALUES (239, 'Vanuatu\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (242, 'Yemen\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (244, 'South Africa\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (245, 'Zambia\r\n');
INSERT INTO `countries` (`id`, `name`) VALUES (246, 'Zimbabwe');